apiVersion: v1
kind: ServiceAccount
metadata:
  name: op-kube-portal-api
  namespace: default

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: op-kube-portal-api
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: op-kube-portal-api
    namespace: default
